import CoreGraphics
import Foundation
import Testing

@testable import RPEngine

/// Pins ``SkinCore`` to the **shipped** UXP panel maths, byte for byte.
///
/// `.claude/agents/coder.md` §"Reuse before writing" asks for the skin-detection
/// maths to be *ported* from `panelpts/RetouchProUXP/skincore.js` "with identical
/// numerics; verify against `panelpts/research/eval.js` outputs". `eval.js`
/// scores `skincore.js`, so the way to satisfy that here is to prove
/// `SkinCore == skincore.js` on the same bytes: whatever `eval.js` measured about
/// the JS then holds for the Swift unchanged.
///
/// The comparison is **exact, not approximate**. Every step of the pipeline is
/// integer or `Double` arithmetic that both languages perform identically, so a
/// tolerance here would only hide a port bug. The three places that could have
/// diverged silently, and are therefore asserted on their own below, are:
///
/// * `Math.round` — rounds half towards **+∞**, unlike Swift's `.rounded()`
///   (half away from zero). ``SkinCore/jsRound(_:)``.
/// * `boxBlur`'s store — the JS writes a float into a `Uint8Array`, which
///   **truncates**; rounding instead moves every edge of the coverage by one.
/// * `median` — `a[len >> 1]` is the **upper** median of an even count, not the
///   mean of the two middle values.
///
/// The fixture is generated by `Scripts/skincore-js-fixture.js` running the real
/// `skincore.js` under Node; regenerate it from a panelpts checkout with
/// `node Scripts/skincore-js-fixture.js`. It needs no Metal and no GPU — this is
/// the CPU half of docs/PLAN.md §6.2 "Sửa da".
@Suite("SkinCore — the skincore.js port")
struct SkinCoreTests {

    static var image: [UInt8] {
        [UInt8](Data(base64Encoded: SkinCoreJSFixture.imageBase64)!)
    }

    static var expectedMask: [UInt8] {
        [UInt8](Data(base64Encoded: SkinCoreJSFixture.maskBase64)!)
    }

    // MARK: - 1. skinScore

    @Test("skinScore matches the JS on every probe, including each early return")
    func skinScoreMatchesJS() {
        #expect(SkinCoreJSFixture.probes.count == SkinCoreJSFixture.probeScores.count)
        var mismatches: [String] = []
        for (probe, expected) in zip(SkinCoreJSFixture.probes, SkinCoreJSFixture.probeScores) {
            let got = SkinCore.skinScore(probe.0, probe.1, probe.2)
            if got != expected {
                mismatches.append("(\(probe.0),\(probe.1),\(probe.2)) js=\(expected) swift=\(got)")
            }
        }
        #expect(mismatches.isEmpty, "skinScore diverged: \(mismatches.joined(separator: "; "))")

        // The probe list is only meaningful if it actually crosses the decision
        // boundary rather than scoring 0 everywhere.
        let nonZero = SkinCoreJSFixture.probeScores.filter { $0 > 0 }.count
        #expect(nonZero >= 10, "only \(nonZero) probes are skin; the fixture stopped testing anything")
        #expect(SkinCoreJSFixture.probeScores.contains(255))
    }

    @Test("The Kovac gates are exactly at the JS's boundaries, not one off")
    func kovacBoundaries() {
        // R > 95, G > 40, B > 20 — the JS uses `<=`, so 95/40/20 are *out*.
        #expect(SkinCore.skinScore(95, 41, 21) == 0)
        #expect(SkinCore.skinScore(96, 40, 21) == 0)
        #expect(SkinCore.skinScore(96, 41, 20) == 0)
        #expect(SkinCore.skinScore(96, 41, 21) > 0)
        // max - min > 15: a near-grey is not skin however bright.
        #expect(SkinCore.skinScore(200, 195, 185) == 0)
        // R must exceed both G and B.
        #expect(SkinCore.skinScore(150, 150, 100) == 0)
        #expect(SkinCore.skinScore(150, 100, 150) == 0)
    }

    // MARK: - 2. classify

    @Test("classify + skinMaskSmall reproduce the JS coverage byte for byte")
    func classifyMatchesJS() {
        let width = SkinCoreJSFixture.width
        let height = SkinCoreJSFixture.height
        let result = SkinCore.classify(
            rgb: Self.image, componentsPerPixel: 3, width: width, height: height)
        let expected = Self.expectedMask

        #expect(result.coverage.count == expected.count)
        var worst = 0
        var firstBad: Int?
        for i in 0..<min(result.coverage.count, expected.count) {
            let d = abs(Int(result.coverage[i]) - Int(expected[i]))
            if d > worst {
                worst = d
                if firstBad == nil { firstBad = i }
            }
        }
        let where_ = "index \(firstBad ?? -1) (x=\((firstBad ?? 0) % width), y=\((firstBad ?? 0) / width))"
        #expect(worst == 0, "coverage diverged by \(worst) at \(where_)")
    }

    @Test("classify's statistics match the JS, including the branches they report")
    func statsMatchJS() {
        let result = SkinCore.classify(
            rgb: Self.image, componentsPerPixel: 3,
            width: SkinCoreJSFixture.width, height: SkinCoreJSFixture.height)
        let stats = result.stats
        #expect(stats.rawPercent == SkinCoreJSFixture.rawPercent)
        #expect(stats.finalPercent == SkinCoreJSFixture.finalPercent)
        #expect(stats.learned == SkinCoreJSFixture.learned)
        #expect(stats.componentsKept == SkinCoreJSFixture.componentsKept)
        #expect(stats.componentsTotal == SkinCoreJSFixture.componentsTotal)
        // The medians are Doubles computed from the same integers in both
        // languages, so they are bit-equal, not merely close.
        #expect(stats.medianCb == SkinCoreJSFixture.learnedCb)
        #expect(stats.medianCr == SkinCoreJSFixture.learnedCr)
        // And the fixture must still be exercising the interesting branches, or
        // the equality above is vacuous.
        #expect(stats.learned, "the back-projection branch never ran")
        #expect(
            stats.componentsTotal > stats.componentsKept,
            "the 2 % component floor never dropped anything")
    }

    @Test("A 4-component buffer classifies the same as the 3-component one")
    func rgbaMatchesRGB() {
        let rgb = Self.image
        let n = SkinCoreJSFixture.width * SkinCoreJSFixture.height
        var rgba = [UInt8](repeating: 255, count: n * 4)
        for i in 0..<n {
            rgba[i * 4] = rgb[i * 3]
            rgba[i * 4 + 1] = rgb[i * 3 + 1]
            rgba[i * 4 + 2] = rgb[i * 3 + 2]
        }
        let a = SkinCore.classify(
            rgb: rgb, componentsPerPixel: 3,
            width: SkinCoreJSFixture.width, height: SkinCoreJSFixture.height)
        let b = SkinCore.classify(
            rgb: rgba, componentsPerPixel: 4,
            width: SkinCoreJSFixture.width, height: SkinCoreJSFixture.height)
        #expect(a.coverage == b.coverage)
        #expect(a.stats == b.stats)
    }

    // MARK: - 3. The three JS-isms that could have diverged silently

    @Test("jsRound rounds half towards +infinity, not away from zero")
    func jsRoundIsMathRound() {
        #expect(SkinCore.jsRound(0.5) == 1)
        #expect(SkinCore.jsRound(1.5) == 2)
        #expect(SkinCore.jsRound(2.5) == 3)  // Swift's .rounded() gives 3 too…
        #expect(SkinCore.jsRound(-0.5) == 0)  // …but gives -1 here, where JS gives 0.
        #expect(SkinCore.jsRound(-1.5) == -1)
        #expect(SkinCore.jsRound(.nan) == 0)
    }

    @Test("boxBlur truncates on store, like a write into a Uint8Array")
    func boxBlurTruncates() {
        // Mean of [0, 0, 1] over radius 1 with clamp-to-edge at x=0 is
        // (0 + 0 + 0) / 3 = 0; at x=1 it is 1/3, which truncates to 0 and would
        // round to 0 as well. The discriminating cell is a mean of 2/3.
        let source: [UInt8] = [0, 1, 1]
        let blurred = SkinCore.boxBlur(source, width: 3, height: 1, radius: 1, passes: 1)
        #expect(blurred == [0, 0, 1], "got \(blurred)")

        // radius 0 or 0 passes is the identity, not an all-zero buffer.
        #expect(SkinCore.boxBlur(source, width: 3, height: 1, radius: 0, passes: 2) == source)
        #expect(SkinCore.boxBlur(source, width: 3, height: 1, radius: 2, passes: 0) == source)
    }

    @Test("median takes the upper middle of an even count")
    func medianIsUpperMiddle() {
        #expect(SkinCore.median([1, 2, 3, 4]) == 3)  // not 2.5
        #expect(SkinCore.median([4, 3, 2, 1]) == 3)  // and it sorts first
        #expect(SkinCore.median([1, 2, 3]) == 2)
        #expect(SkinCore.median([]) == 0)
    }

    @Test("keepBigComponents measures against the total skin area, not the largest blob")
    func componentFloorUsesTotalArea() {
        // Two blobs, 100 px and 30 px, 4-connected and far apart. At a 2 % floor
        // both survive (30 >= 0.02 * 130 = 2.6); at a 40 % floor only the big one
        // does (30 < 52). If the floor were a fraction of the *largest* blob,
        // 0.40 would keep nothing but the 100.
        let width = 40, height = 10
        var mask = [Int](repeating: 0, count: width * height)
        for y in 0..<10 { for x in 0..<10 { mask[y * width + x] = 255 } }
        for y in 0..<6 { for x in 30..<35 { mask[y * width + x] = 255 } }

        let loose = SkinCore.keepBigComponents(
            mask, width: width, height: height, threshold: 60, minRatio: 0.02)
        #expect(loose.total == 2)
        #expect(loose.kept == 2)

        let strict = SkinCore.keepBigComponents(
            mask, width: width, height: height, threshold: 60, minRatio: 0.40)
        #expect(strict.total == 2)
        #expect(strict.kept == 1)
        #expect(strict.mask[0] == 255)
        #expect(strict.mask[30] == 0, "the small blob survived a floor it is under")
    }

    @Test("areaDown maps a source pixel to floor(x * target / source), like the JS")
    func areaDownMapping() {
        // 4 -> 2 is an exact halving: cells are {0,1} and {2,3}.
        let rgb: [UInt8] = [
            0, 0, 0, 10, 10, 10, 100, 100, 100, 200, 200, 200,
        ]
        let out = SkinCore.areaDownRGB(
            rgb, componentsPerPixel: 3, width: 4, height: 1, targetWidth: 2, targetHeight: 1)
        #expect(out == [5, 5, 5, 150, 150, 150], "got \(out)")
    }

    // MARK: - 4. BodySkinMask, the RenderMask wrapper

    @Test("BodySkinMask puts the classifier on a working grid and an affine back")
    func bodySkinMaskGeometry() {
        let width = 1280, height = 853
        var rgb = [UInt8](repeating: 0, count: width * height * 3)
        for i in 0..<(width * height) {
            // One uniform, unambiguously skin-toned frame: what the mask *is* is
            // measured in SkinSyncBenchTests; what is checked here is geometry.
            rgb[i * 3] = 214
            rgb[i * 3 + 1] = 168
            rgb[i * 3 + 2] = 146
        }
        let result = BodySkinMask.make(
            rgb: rgb, componentsPerPixel: 3, width: width, height: height)

        #expect(result.mask.width == 320, "the grid must be skincore.js's SMALL_W")
        #expect(result.mask.height == Int((853.0 * 320.0 / 1280.0).rounded()))
        // The affine must map the mask's far corner back onto the frame's, or a
        // whole-frame mask lands on part of the frame.
        let corner = CGPoint(x: CGFloat(result.mask.width), y: CGFloat(result.mask.height))
            .applying(result.mask.maskToImage)
        #expect(abs(corner.x - CGFloat(width)) < 0.5)
        #expect(abs(corner.y - CGFloat(height)) < 0.5)
        #expect(result.coverageFraction > 0.5, "a frame of pure skin came back \(result.coverageFraction)")
    }

    @Test("A mask smaller than the working width is classified at its own size")
    func smallerThanWorkingWidth() {
        let width = 64, height = 48
        let result = BodySkinMask.make(
            rgb: Self.image, componentsPerPixel: 3, width: width, height: height)
        #expect(result.mask.width == width)
        #expect(result.mask.height == height)
        // No resampling happened, so it must be the fixture's own coverage.
        #expect(result.mask.values == Self.expectedMask)
        #expect(result.mask.maskToImage == .identity)
    }

    @Test("The float-RGBA entry point agrees with the 8-bit one")
    func floatEntryPointMatches() {
        let n = SkinCoreJSFixture.width * SkinCoreJSFixture.height
        let rgb = Self.image
        var pixels = [Float](repeating: 1, count: n * 4)
        for i in 0..<n {
            for k in 0..<3 { pixels[i * 4 + k] = Float(rgb[i * 3 + k]) / 255 }
        }
        let fromFloat = BodySkinMask.make(
            floatRGBA: pixels, width: SkinCoreJSFixture.width, height: SkinCoreJSFixture.height)
        #expect(fromFloat.mask.values == Self.expectedMask)
    }
}
