// GENERATED by Scripts/skincore-js-fixture.js — do not hand-edit.
//
// The inputs and outputs of the **shipped** UXP panel maths,
// panelpts/RetouchProUXP/skincore.js, captured by running it under Node. It is
// the same file panelpts/research/eval.js scores, so pinning `SkinCore` to these
// bytes is what .claude/agents/coder.md §"Reuse before writing" asks for:
// "port to SkinCore.swift with identical numerics; verify against
// panelpts/research/eval.js outputs".
//
// Regenerate with:  node Scripts/skincore-js-fixture.js [path/to/panelpts]
//
// Branch coverage of the 64x48 frame below, asserted by the generator:
//   stats.learned        = true   (the CbCr back-projection ran)
//   componentsTotal      = 3      (found)
//   componentsKept       = 2      (kept — so the 2 % floor dropped 1)
//   rawPct / finalPct    = 44 / 27
//   gain                 = 1
//
// Node v24.2.0.
enum SkinCoreJSFixture {
    static let width = 64
    static let height = 48

    /// Interleaved RGB, row-major, row 0 at the top — `classify`'s `buf`.
    static let imageBase64 =
        "Q1JgQU9bP1NdQlFgQExkQE9fQk9gQE1bPktfQ1JdP1BfP1JgQVFePkpiQk9lPktkP0xgPk1gQlJhO1JdPklfOUxlOk9e"
            + "Q0tiQFFbOk9lQkpiQ01eQklkP01lP01lQ09eQkleQFNlOlNfP09kQlNePFFbP0xlQ05lPEllxZtfyJlix5lcxJhhwJpg"
            + "x5FjyZFgwZlkyZpkxZZdyZVfwJNkxJVfv5pkwZRgx5ZhxpdcxplcwZljyJRlwZJkwZNdwZdhQlJfPkxiP0pcPFJePEpd"
            + "QEtlOVBlPEpcQU1hQVBhPUtgPE5jPUxbQU5cQk1dPE1jQE9cQEtfOU5cQ1BkOUxkQVNbOk9jQ0lhO0teQVNbOlJdOU5l"
            + "PkpeQVFiP1JjOk1dQk1dQVFfOk9gQ0teQVBbQ01cQlFkP01kQE5fyJFhxppgyJtkyJRbyZRcv5Rcwplew5RdyZliyJRb"
            + "x5JgxJdiwpJexJtdyJdhyJRiyZJgxpFjx5NbwpZbwpFjw5Zlv5tcPU9lQlNfP0peQlBcO05iOVBlQ0pcQE1bPktiP0ld"
            + "PU1dPFJeP1BdQ05kQlNeQVJiPEphO1FiO1NfQUplP01iOlBeQUtkOU1lO1BeQVJhQkpiQUpiQkxiPlFiQ1FkPU9gPU1c"
            + "QVNhO1NiQVNgPVFiPUxcOVNlP1NhO0phwphiwpJlwppgyZVgyZRdx5ddyZFlxpdkv5RiwJJhwZlhyZdhxJVbxJhiw5Fj"
            + "yZpfwZFgxpFcx5tgxptgwphixptiyZZgQk5kPFJhQUxfQVNeOk9bPU5dQU9lQVJgQ0xeQFFeQktbQk1lPkldQFNgP0xi"
            + "PVNlPVFfPFBbO0xbOVFlQElgQFJcOUleQ0tfPUxgQ1FiP1BiQE1fOlBcO01iP1NcQkpfQk5hQVFcO1JdQ1NhQU5kQ0xc"
            + "QUxcQUlgPkllxJtixJFlyZNgx5tjv5hhxpVjw5hbxZdjv5tfv5pjwpJbxpdkwZZhxJFhxZVjwZtiwZdkyJdexZRew5Nc"
            + "xpZcwZhhv5NbO09eO1FhO0pcP1NgPEpbPlNcP1FjQlJiQ09fQE1cP01iPU5jQUlbP05lPVJlQFNiQ1NdO1JeQ0pdQFBb"
            + "06yWQkthPk5cPlJgP09fQEtgPkxhP05jO01gO09gPE5fQkplOVNdPVFfQk1gPkpkQ01jP0xeQVJkPkxkQ09ixpVcxpJi"
            + "xZpfv5pcxpRfv5NkwZlew5ZdxpRjxZJfxZJdwZFiw5Jiv5lfwpJjyZpixJdkxJJcwJJlw5Jkx5FdwJVcx5ZbQ0xbOVBj"
            + "Pk5eQ01hPkpkQ01cP05iOlJlPVBjQFNdOUpjPU9lQVJdQUphOU5hPE1k2KqT1KmN1aqT0aWW2auR06SP1KaN2aeU1KWS"
            + "P1JjPE1gOUxiPk9lQ0xgQEthQE9iPktdOktiQVFjOlBcOlNkP0xhPklkP0tbOlJdwZRbxZhdv5hgwJtcwZpew5JfyZth"
            + "xJJbxZFcxZFhyJdkxZtlv5Jew5NgxJJbwJNcyZtbwJpex5thwpNgxJdeyZVewZtdQEtbPkxkPFBgOVFbPElkQE5cQk5k"
            + "QE1ePkxlPEpgQkpbQVJfQ0phP0pl1qeR16mO1aOQ2quU1qaU1aqV16mU2qiS1amP16WW16qQ16WW2K2OPkljO09cPk5k"
            + "PkleQE9lOU9kP05gQklbOU5kOVJgPFJcQlJlP01ePE1hxZhlxpNlwppgxZZgxJpkw5ViwJJdwpNixpRhw5FgyJFjxJtb"
            + "v5hbwJJgwZFdw5Jdx5Fbv5pbwZdeyJRexZFgx5phwZJiQk9dQlBiPU1iQE1hOk5dOktjP09hQFNiOkxlPlFgPE9jPFNl"
            + "QEtk26yP0aqS06yQ06OX0aWQ1aaX26WN2qWO2KqT16WR2qeO2aSS0q2S1qaR1qSVPUxfPkxlQk9eOk5eQkxkOU1cP0lj"
            + "PE9bOU9jQEpdPFFiPFFbO1NdwJJkxpNhv5tbw5tlyJZew5lhyZJdwZFexZFcxJViwZRbxZpiwZldzqKLv5dlx5dkwZlf"
            + "xZRkyJdgxJllwpZlx5VewJhcPk9dQlJePlNfOUpiPU9iOUldQkxkPVJiPEteO09gP0tkQ0lk1aeS2qWS1qiW2KaW26uO"
            + "26aP2qyV26SN0aSS16uV16iV1aaT0aWR2aWN26qP0aeS0qSPQlBhOVNhO1JcQ0lePlNcQEllP1JjOVBdOVBiPVNkPFBi"
            + "PEtewJFgv5FgwZtexJVdyZtdv5pdxphewpRkwZVdw5dgyJZcx5Zb1KOH0qOHzaGOwpZdwJRhyJZjx5dfwJdgyJhlxZNj"
            + "wJRbQFBeQ1BhOk1gP0pbOU5kOU5gQlBlQlFdQ0lbO09iQUtj2KuX1qWT1a2T26ST2KaV0qeT26yQ2qeV16uP1KWR1quT"
            + "162N1KOQ2aiS1KOP1aWS1KSU262O1aeSPEpkO01cQlBjQE9lOkldOlBdOVFcPlBlOlBkPU5dOkpewpRgwpRhxJllyJpk"
            + "xJVbyJViwJllwphgv5piwZZkw5pey6KJz56F0J+PzqGF0ZuHx5Vew5Vgx5JdwZJlxJpkv5leyZRhP0tcPklfPVJkOUte"
            + "PExbOVBcQk1kOlJcOUpiQExe2KSP06aO1a2T2a2R16eW1KiO0qWX1qmP1KSQ26eV0qaP2KuO1KON1auN2aeS0qmN2q2V"
            + "26iX16SR2quS26qXQFBcOUliQ0ljPEpfQ09gPEtkPVJiQkxiOlFeQ1JdxZZjwpNdv5Vew5FjyZdewphbw5JkwphiwJNl"
            + "yJJjw5hdyZFjzJ6LzKKH0Z+OyJtbwpVkxJZbwpFfxpNfx5lhx5VdwZVdOk5hQ1NjPkllQFFbQ1JiQEphQEpdP1FeQExd"
            + "OlFj2aaW06SV2KSP2qeX0qmT2KOS1KOV16SS1aqN16OQ2KaV1q2O16iN16uR26iU06yX06mS2qmR162V0amQ06uTPlJd"
            + "O1JdOU9dOU5lP0phPk5iQEleO1NkQ0llPFJgxppewZNexJddwJJgxptgyZlbxJdiyJtbwJJbxZFlxpNlxJdbv5Fi1KGH"
            + "xZdbyZNhyJVlxJtew5plyZdgx5hix5dgyJNiQkliOUpfQE9gOU1bO0tiPExfQVFiOlJfQk5d16qQ2KiN2auT16WO2KuQ"
            + "16yX2qWV2q2U2KOV2qOS1aaP06yR16eU1qmS2qWX26yV2ayT0qmW1KmS0aWS0auR1aST06eRQkxbOk9gOVJdP1JlOU5j"
            + "QkpkOlFdQ0xjQkpcyJlgv5pbxpRbyZhlxpNcwZJexJFgwZNdx5Ndx5FjwJlewZlhyJNdw5Fhx5tjxJJixZFbyJpcyZNe"
            + "yZpeyJRdxJZlxJRdPFNcO1FeQ0lgP05iOU1kOk1fPFFkPFFePExg26yQ2qiT2KaV1qeP2KWS1aaU16eQ2KaR2aaV2KqX"
            + "2aeT0qyX0qSO2qyW26WQ1qeR2amP2KqO0amO26eX1KiW2amW0q2RQlNeQ05fOlFcPEpfQ0xjQlNfQktcPVJjQ0plwpZe"
            + "wJdiw5ZdxJpgwJdgyJJdw5Jfx5tbxpJiv5Nlw5dbwJlexZZkyJFiwpNexJJhxZlgxZNfwppgwJVkxJtfwJlfv5JfOVFc"
            + "OU9fQ0lgQlBlQFBePlBlO0thOVJk1aiO0aWW1KmP2qiN0aaO1qOR0aSO1KyN1ayT1KaO26uX26eO2quV2amV16uT2qSW"
            + "1aeV2aWU1qyN2KuV16iV2aqO16WN1auR2KuSQlJjQlFbPFJfOlJbOU1lPE5fO0xhO1JhxpNiwJtbyJtewZdfxpNeyZlh"
            + "wJtix5ZjyZhex5Niv5lcyZFdwJVix5hlyJNgwZheyJdcwpZjw5Vlw5NbyJJgyZdgwpVgOlFdQVFiPFNePExbQlBgO1Bk"
            + "QFFcPE1l2qqR2aWQ0qeP26eT16SR16WW26WR2a2S26SX1qyV1quX0qqO1ayU2qeO1qOX2KWR06eS1auP2KiW2aWU1KuQ"
            + "06aO26qN1KOQ2qiOQVNhOU1fPEljP01gPkxjOlJlOVFdOVFkwpVbxZNhxJdjxZhiv5RixZdhv5Rhx5FfyJRgw5tiyJJg"
            + "xJlhxJlgw5tlx5RfwZVjyJNgv5pew5VbwZFkwZZiwpdfv5lbPUxhOlJbQk1gPEtlOVJgQlJgQVNkP0pd2quR0q2X0qOS"
            + "0auS16iN16WX262Q06SV1KyX16qX06OU1aiV06mW2qWS1qSV0aiQ26yQ0aeU2KWT26aO0aWP2aaS1qOU06qV0aSSPkpk"
            + "O01bOk9jP1BkPVFkQlBbPUleQlJhxJNiwJlcwpVlxpFhxJVgyJFbyJtbwZdfxpNexJFexZNlxpNdx5tbwpljwphbwZdc"
            + "w5NkxZdkw5hiwpJfwJNdxJlfv5lgOlBlP0tcO1NdPE9bQUllO01iOVNiOUxh0qWV2qWO2aiU2aqT1auR26WU0qeX1amW"
            + "06WQ26WR1KqP0qWU1qyQ0qqN16WX2qWP0qSS2KuO16SN2auP26SU2qyV0q2U1aqP26eXOkldO1NhOVBfQ1NdQkteOlJh"
            + "OktkOU1dxZJkwpNjwJtiwpZgwJRbwpFgxZhiwJJhyJRcwpVcv5pfwJdhxZdcx5Rcv5ZiyZFexZJcyZZcw5dfxJVexpJg"
            + "xJlkv5hdQE1ePk1dOUtiQklcQExjOU9lO0plP05i2q2R2auO0aqO0aiO1KeS1qqO1KuS2auN2KiU1qeO2KWS1aSP2KaT"
            + "1KWR1qSQ1KuU1ayT2KeV06iR2qSR1KqQ1aqX1qqW06aO06SXQklkQUpdQEtlQ0pcPVFeQFNfP0xgPVFcwZJix5tkyZde"
            + "x5JgyJdixZpfxpNdwJFfwJtiw5pgyZlixZZgv5ViwJRew5lgwpZeyZZfw5FexptgwJZiwZVfyZtbyJdiQU9hPk1lPFNb"
            + "P0xhOlBlOkplPkxjPUpj26mX26WO2KWS2KOV0amN1KeX262W2qyU1aiV26qQ262T2aWS0qyX16yV1aeV0qOQ2qeP2q2S"
            + "0qeX2aaT1qSU1a2V1qqO2auV06eWPU9fQEpbPk1hPU5kQ01jOklkQUtdPFJhw5pjv5VgwZFgxpljx5Fbw5Vgx5lcxZJi"
            + "wpNgwZReyZtkv5lbwJFiv5tixZNbxpRdv5phxJVlwZZlw5JiwZpeyJdewZldP1FhOkxfPE1kQFBfQ0ldQFNbOk9e26uO"
            + "16OO0aqT06mU2aaV2q2Q16yR2KSR0qaW06qN062X1aOR26SP26aQ16qT2qaS0qmS26WV2a2Q2KSN0qqV06aW1amU2aOO"
            + "162V2aqX26yPPFBdQ0pdP09hQFBbOVBjOVFgO0thQU5bP1NgPkpfQ0xhPE9gQkxbQ1BgP1FiOkxiPE1fP0pfPUlfQUli"
            + "QExkO1BkOk1bP1FlPlJkOlJdPlFkQlBgPkljOlFgPUlbQlNfO0pjQVBcPlFdQlFbPEtkOVBb1quX0quU16eX26uO0qyT"
            + "06eQ16uU1KaV06yR2KyV0a2N2KyU1qeX2qqN2qmR1aaN16yN0ayQ06mO1q2O0aqV1amT0amT16yR1aWXPU5hQEpdPE1b"
            + "PkljOVFkO1FkPUliQEpjPkxcOkteQE9iP1FcQlJiQFNhPUpjQk9jPU5dQ0tkQlFhOk5iQ1JkPktdQE5kO09iPFNbP01e"
            + "PU1gO0xhPVBcPVNlQ01bPUpcO01kOlNkPVFbPU9bO1BgQ0xfOk1l2KiX0aeS2amP262V1KmO162V2qiN2qiS0aSQ1a2N"
            + "16yR2qqN0a2V1qSR1qiO2auS1auP06WU2amV2KyN0aWS0qOO0qWU1KuS2aqXQUldPk9bPUpgOUthQk1jO1BjO0ldQ01c"
            + "O05lPE1jPlFbPklgOU9lPkxcOUlgQExiQlNhQktiPlNdOk1kPU1jQlFdO05bQlNcPU1iO0xjPEpkPkthO0lePk5lOUlj"
            + "PFNjPkxjP01fQlJdOVBgPU1bP05dO01j06WX1qWV0aSV26SS26qN1aWV06uT0qyP16qS26OU0aWR2KSX0qqP06WR16mV"
            + "1KqQ0qiX26yO06iW2q2W1aWT1auP262X06iV16uSPE9bO1JcPFBdO1NiP01gPlBbOlBcQVBlOlBePkpcO0ljQFNbPU1j"
            + "QE9iOVJiOU9lPFFhPE5jOkxbPVNbOkxhO1NbPU9gP0xiOk9bQ1FeQk1bP0tkQUthPFNeP05jQEthP1FkPlFgQEllO0pe"
            + "PFJbQ05gPUlg0qiW2KSR06SS1qyV1qeT2q2N0auQ26yR2qmT1aiQ1qeO16SV2KmU1qyO2KiQ2KuN1aaV0q2W06aO0a2R"
            + "06qU0qqQ0qaN0qiT0qiWQFJlQUliOVFiPk9bO1BfQ0piOVNkP1NhQFJlPlFhO1FfOUtbQUtgQlFdPFBkQVFgPlNgQFBe"
            + "PE9bQE9fO1FkQVJeQEtfPlFePkplQEljPEljP1NeO0pkQ1JcQVNlPUtiP09eOVNjPklcPlFeO1FgPUpgQlNk1qSO0q2X"
            + "16eN1aWP0qiW0aqV0aeO2KON2aOO0qiU2aiU16WT1aOO1qWV0quS2auQ1K2O0aSO2qmW16eR2KyO0qSS1aqN2KmS1qmT"
            + "Q0pbQU5lPE1kPk9eO1JfO0pkP09jQU5gOUxiQlFdP1BfPUtePlBlPU1lQkxiO1BgOUpiQVJbOVFlPU5kQFFfPExhO0xi"
            + "P0xjP0plQ0pkPlFhQ0xlQlBgQU5jPE1bPkpiO1JiPk1lPkpdOlBdO01jOUpbOU5i26qW0aWS0qqV262X1qOQ0qiW1ayP"
            + "2aaR2a2V06WP26OV0qiO06WV2qeO2KqS2aeU1KqV1aST2a2R1KOW0aSP0qyN16eV06yU2aWXPFNkQ1NlPlJbPk5iP0ti"
            + "QkljPFFlQ05gOU9bOU5bOU1gQk5gOU5eQUpiQU5bPFBbQkpbP05cQk1jQlNjO1JeQk1lQk5gPlJdQVNeO05hQFJjPU9k"
            + "OVNjO01gQktgPU1kQ01eO05iPEtlQktdQVNeOUpjP0piQ1Ni26SR0qaQ16SO2aeU0auQ06WU26eS0qqR0aqW2qSU1aaS"
            + "2KqR26mN0q2N1aeV0qOX0aeQ2qSP16mQ1KWU26qN16qV2KiWOVFeQE9kQ1FcPFNdPkpfP01ePlNjQE9cPktdQFNdP09c"
            + "PktlOUljPE5bQkxjOUlfQU9gPUtjQ1BgP0pfQExkQk5fQkpcP05lO01jQ0xhPkpkQk1ePVBiO1JkOlJiPkliQU1bPEpj"
            + "PElbPk9jPFNkP0lbPkliOk1iQ1Bg06eV06yT06aS2aeX26mN1KyQ2KWV2K2S2qeP16aX1K2R0aWR1aOQ16OO1qSX16iR"
            + "1KiU262Q0aeR26qX1KOX2qeW16mPP01eOU1dPlJkP1FgPVBkO0xgQk1iQVBfOUlkPU1jPE1iQlFeO1NbP01ifFtLQ0lg"
            + "OVNjQ09cOUtcQ0tkP1JePk9fQk9fQlNbO1JfPE1hP0pePFBkOUliPUxkOkthPk1kO01jQ0tbQ09ePlFhQktlPlBdP1Bi"
            + "QE9hPVBjO1Be0aqW2q2P2KOS2aiN2aqT2KqP0qST2qWU0qqP1amX1quV1amX2KaU0qyN1aeR0ayR2a2S1aeP26eP06mU"
            + "1qWOO0pgPEllPEthPUtbQUpbPVNgQ1NcPUxdOUplQ1JiQU9gelNMfVJEdFpJeFpLdldHdVtDdVVEfFRDeVhDQVNiPVNf"
            + "Ok1cPE9cPU9iPktbQ0xiPEldQk9dP09iO1FePVNhOlFjPVNfOUtbPU9fPk1iOlNhOVBjPU9ePEtdOk5hOlBl06aW0aeR"
            + "2a2X1qWR16yO0aiO1KaS1KqP06uW26qS1qSU1aaT1KeS1KuR1amU2aWU1K2X0qSP1amO16WW0qWPQUtkPkpbPklePVNb"
            + "PE5cQUpgQ1JfOUtkOVFde1FLfVhDdFlKeFJLfFhMeldKfVhFfVFLe1RKfFlEe1FFeFNLdFhDQlBgPU1lPEldPE9kO0le"
            + "PFFbQ1FbOlNhQk1lOUtlOUliQUpgO0xjQFFePFJcQExfOUlcOlFiO1FeOVNhQE9bO1Nf26SU2aiR16iX0aiP2KeU1KqV"
            + "1aeP0aqS2aeU0ayV0quP2KqW16SW0qWU0qOT1KiV2aaQ2KiN2qaPPktkPklbOVNjQk5kOktePk5hOktcOklhO0teelpI"
            + "fFpLeFtHeFJGeFZEfVdCeVdEfVtJdVdHdFhIfFpGdlNKfVFHdVVGd1NFP1BdOkthOVNhQlBdQVBiPU9eQ1BhQUlgP1Bk"
            + "Q1BcPExbOUtcPU1fPFFbOklcOU1bOVFlQFFkPFFgQlFbQExkPExg262S2KeT2auW2qqO2a2N16SU1K2Q1qyS262X2KiS"
            + "1K2P1KST16uV2qyX16eW0qaO2qaTOk9hP0pkQ1BdPUpfOVNfOkpiOktkQU1lQk1ee1hGeFNFfVhJeVdHflFCelVFelRC"
            + "elNGdFFGdFFKd1hMe1JId1pHfVlCfFVIelVJeFhEOlFjQUlhPUlkOlJePElgQ0tfQ0lkOk5jPklhOkplQ1NlO01gQ05g"
            + "OU5lOVFjOktbQFBfQE9cPU1lOU9kQ09gQElh062S0auO1qiS16qN2qiX06qX1KeV0a2Q2aOT1aeW2qqT1KuV1aaW06eO"
            + "2aWTOkpcO0lgQVFcOVNlOk1gPFJhO05jPFJjQExdeFtEdlhJfldKdVVKeVNKellKdFVMflpFfFhKflZJelhDdlJCfFZF"
            + "fFpGdldMdlFGe1FCflVHdFNCQlJhP09hQU5gOU5hQVBbOVJdOUpkQUpfPU9dQE9cQ0lgQVBlQk9dO1NdPktgPFJlPExd"
            + "PklfPE5cQUplP1BiQk9h2KyN2KaN2amR2KWW1qeO0qiS2aOV2KaO2KqT2aiN0qyN1quS2K2OPEteP0pcQlFjOUlgPEph"
            + "OVNgQE9jPE9jOUxjQU5eflNDdFdMflRCeFVFdFpEfFFGdVpJeVJMeVRCfVJHfVlHfVdMd1tJelFHd1FHfldGeVZHfltF"
            + "flVEP1BlQ0pdQ1BdPFFbQ05fOUlbP1NhPUpkOUphPFNgO0tbO1JlQ0xcQVNkPE1dOk9dPE9hQE5fP0tcP01iOVFgOVBk"
            + "Q1FiPE5l0aOU062O1KWX1qaQ2KmV2aaX0qSQ1aaV16WNQUljOVNeOk1dPU1cQlFcPFNgOU1iQExjOU9fQk1hO09iPU9e"
            + "elNDdVhKdltLfVtKeVtJdFtGdVRKeFtDdVtHd1ZCe1lFfFpJfFJJelRLdVtDdlNFfVdLeVtGeFFIQ0pfO09eQlFdPk1d"
            + "Pk1iP1JgQ01lPFBiPUxbQVFeQElkPk5cPFFhOUtdQk5hQlFbPFNlQ1BdQk5hOlNjPE9gQUpdQFJbQExiPVNiQU9dP1Be"
            + "PlNh2KmNQE5kPk9bQ1BeQFBgQU5iQ0lkQlNjOUpfQ1NfOUlePVBhPk5hO01iQUtjQFFleVlMeVFGdlJMdVpDd1NDflhJ"
            + "dFFMfFdKfFNFeVRJflFMdVlJdlJFfVpGflJFdlFFdVVDfVpLdVhCe1tDeFRMQUxlQ0lgQElbP1JhQktiPVJhOlBeP0tg"
            + "Ok1dPE9jP0pdOlNbQkxcOkpiQk5gP0tcO01fO0xcPUldQ0xjQ05gQ0tdPFNkPVBjPk1kOlJePFNfPFNbQVJbQUtiPFBc"
            + "OktiOk9gPFNbPVNbPE9gOkpcPE5eQlNkPUtgQExdPlBhQFBfOUlcflJCelNCeVdGflRLflRCd1tKfltFdFlHflVLd1hK"
            + "eldLelNGeldGeVlDelJMd1JFd1lHd1JGeVZKOk1kQktdQU5lQk9bPVFcOktlPE9iP01lP01hPE1lPVNgPktkO1FhQ0xl"
            + "PUtgPUxkQ0xbPEtkQFFgPEllO09hP1JlQUldOUlePVNlQExiOUxiO0tgQEpePkxlOVBbPE5jP1JcP0tkOkphOU9gQFFk"
            + "Ok9cQUliPVBiQE5jOVJfQUtbOU9eOk9ffllCdVJJdlZKeFlDflVLd1hEdlFMeVpKdVdMfVpFeltKdVhLeVRGeFhMfFlE"
            + "e1FJd1NHeFVFflpLPVNlPEpdO0tfOkxePE9fQU9fQVNgPk1dPlNhQVFkOkliQk5hQ09bQ1FgQE9iPlJfPlJcOkxePk5l"
            + "PktcQlFkQ01fO0tcOVFiQUphQFNfPEpiP05lPktiO0ljQU5bQk1kQU9gQU5dQ1BhPkpbOlNkQUxcQ1BlPlBlO0tlPUxi"
            + "P1BhQE5kQ0tdflVJeVZIeFJMdFZEdVFIflNGdFlMdVtHfFpCdVRKeVpCeFRJeFJMdVtLeFJJfVJHfVpLfVJDelVFPUxe"
            + "O05kQlFhQFNdOkldOVFdPE9dQ05gPk9cQE1gP0xbO0tdQUpcP0pcO1FkO0xlO01eQEtiQFFdQkxiOkpfOU1jOkplOkth"
            + "QEpgQUlkQFBdPFBgPlJeP0xjO0piQ01cPEtgO0xfQ1JhPU1gQ0xcQUljOUxcPlJiPlJcQU1fPkxdP0xlO0xhOkxjdltI"
            + "d1pLeVpHdVlFeVdFeltCeVRMdVlLfFhKeFpIe1ZDdFVKdlVCeFlFflpIeVpFfVlMQlFcPUtcOkxfOklgP0xkPVNiPkpk"
            + "OU5gO0tdQEteQk5bOkpfOVNcP01kPk1iOU9iQ0xbOVNfQFFgPEtcO09hO01lQ0tdQVJlQExbOUxdQ0tfPE1dQ0pdPVFd"
            + "QUpiO0pbPlNkOlNdP0pgPlFiPFJhOlFbOlNlPU9lPlFhOVBbO0lkOlNfQkllPExcP1NjQ0xddlNCd1tEdVZHe1dGdVhH"
            + "fllFdVJJflRCdVtJd1pGdlFGdVdGeFZEeldEelNLQlNiQ0lhP1JlQUxhO01bQlNhQVJfOUxgOk5eP1JlOU9jPk9dOU5g"
            + "Qk5lQFJjO0tgPVFlQUtgOlJcQ1JkP0pdQE1jQ1BlQFNgOk9lPFFcPE1fQEtkOlBjPUpgPlFjPVFfPlNjOktlOU9fP05g"
            + "Q1JfQFBlOlJbP1NcO09bOUpkQExlQUphO0lePlFlOlNbPE9gPU9cQk9jfFRGeFlCdVNFdllCdFFJdFpCeVNCelFEfFtK"
            + "eVdKeFZKdVFLeVNIQk5bPVNfQE5gO0pePFBiP1FkP05iOktkO1BbOU9lPkxlOVFhP1JkPE9lQ0lhP0pbQ1NfPkxcQFBf"
            + "O0peP0pcPUplQklfPk5cPlNjOktbPUxbQVNjPE5jOk1jO0llQVFfQklgOVNlPExgP0xgQlJgQFJdPU9eQU5iQ0lfQkpg"
            + "OUpdQ1BdPFNbP0tdO05cQFBjQ1BbO1JkQlBdPVJiQFJleFRHdVJMflJEeFVGfllDd1lCdlVCdFJEd1pEO0lgPk5fPEpb"
            + "QU9gOUtlPlBlO1BfO1BbOk5gOkpgPlJdQ0tlQktjPkxjOktdPUtkQklgOkxdQlJjO09dOlJfPE5iO1BhQUxbQFJfPkxg"
            + "OUxlP0pdQUldO1BjQUplOUxcPEphQk1bP0tfQ1NhPk1fP1FbQVNeQE1eQ0piPlJfOkxbPEplO1JkPFFeQlJhQVFeO0pf"
            + "OUlgPE5jOlBhOkxkQlNbO0pjQ0llO09lPUpfOVBcellFQktiOlNgO05kO05jPU9jQExbQlJfPFNhQFBeQlNkPEpdQ0tf"
            + "O1NlPFJhQktjOlNhPlFiPkxkQ05jOlFgOU1dPk9eQ05hQ1FgQ01dQE9bQ1NhOk5cQVBjOk5fQU9kQ0thQU5iO1NeP01l"
            + "OVBeO01dQVFlQ05eQExfP1FeQUxiOkldOUtcQE1hPktfQU9cPE1cPkxgQEphPkxiP1BkPUllPU5iQFBhP0pgQ1FbPlBl"
            + "O1BePEljQ0lgP1JdPk5bQ09hP0ljQklgQkxiQ05gQEpjPkthPkxcQEldQ09ePFFcQExkQU1iO0ljPExcQ0tbQ0lkOlNf"
            + "PU5bPVFjOlJjOU1fPlJbQVNbQ0tlP1BkOkpcP0lfOlFjPU5hQkxkQE5jOVJeQlNiOlBkQklhOU5gOU5bOkpbP1FiPkxf"
            + "QVFhQU9jQEldO0pkP01kQk9gQUpcQFJbPVFcPE9eO1BgQUtbP1FbQE9gO1NiPE9fO1JkQ01hOklePFBlPE5cO0llOU1e"
            + "QktlO0pdQk1jQk1cQExdPVFcQE5kOklcQlNgPFFcOkllQFJhQ1BbOVFiOVNkQ01gQFJfP0pdOlFbQ1BbPUtiPE9lPkxf"
            + "Q09jQlNbOUxdPVFhOU1dO0pfOVFiPU5fQFFeQUpeP09fPFJcQ0ldOU9gQU1cQ1FhQE1kO1JgQUxkPlFlQktfOlBcOU1d"
            + "QUtkQ09lOk5dOUliOk1bQ01iQ0tcOVBkQkphO05lQ0xbP1BkPUtdPk5jPk1lQ1BcPFJhP0tfPkljQ0pgPE5kQktbOVJb"
            + "P1NjPUxeQVJdQExlQ1NkQE9bO01lO1JkOU5fQ1BjQ01cPFJfP1Ni"

    /// `skinMaskSmall(classify(...))`, i.e. the coverage map the panel writes
    /// into a layer mask. `width * height` bytes.
    static let maskBase64 =
        "AAAAAAAAAAAAAAAAAAAAAAAAAQEBAQEAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
            + "AAAAAAAAAAABAgMGCAoLDAsKCAYDAgEAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
            + "AAEDBQoOFBgcHyEgHRkUDgkFAgAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAEECA8Y"
            + "ICoyODs/PDkzKyAXDwgDAQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAEFChQgLjtJVFxg"
            + "ZWJdVUo7LR8TCgUBAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAIFDBcmOE1ecH2HjJGPiYBy"
            + "Xks3JRYMBQEAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAEFDBkqQFdwhJWiq6+zsq2lmIRvVj4p"
            + "GAwFAgAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAECxcqQlx3kaOyvcTGysrGwLakkXdbQSoXCwQB"
            + "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAACCBUnQF57lq29yNDV1tra19TNwK+Xe11AJhQJAgAAAAAA"
            + "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABBQ8hOll6mLDEz9bb3t7g4N/e29LGspd4WDkgEAUBAAAAAAAAAAAA"
            + "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAgoZME5yk6/E0tjb3t/e4ODg4ODb1Mavk3JOMBoKAgAAAAAAAAAAAAAAAAAA"
            + "AAAAAAAAAAAAAAAAAAAAAAAAAQUQJEBjiKjA0Nnc3d7f3t/f39/g3tvSwaeIY0AkEQUBAAAAAAAAAAAAAAAAAAAAAAAA"
            + "AAAAAAAAAAAAAAAAAAIJGDBSd5u4zdjd3t/g4N/g39/f4N/e2c24m3dRMRgJAgAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
            + "AAAAAAAAAAADDSA8YYeqw9Tc3+Dh4eHg397d3N3d3dvUw6mHYDwgDQMAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
            + "AAAABREoRm+UtMrY3d/g4eHh4N/d3Nvc3N3d2cu1lW5GJxEEAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAYV"
            + "LU54nbvP293f4OHi4eDe3Nva2tvc3dvQu553TSwUBQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAIGDJVgKPA"
            + "0tzd3+Dh4eHg3tzb2drb3Nzd08Glf1QxGAcAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAACRs1WYSnwtTd3t/g"
            + "4ODg3t3b2tra2tvc3dXEqYVZNRoIAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAocOFyHqcTV3t7f39/e3t3c"
            + "3Nzb29vc3N7Yx62JXTgcCQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAALHTleiKrE1t7e397d29vb29zd3Nva"
            + "29ze2civjF86HgoAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABCx46X4mrxdbe3t7d29jY2drc3d3b2tvb3trK"
            + "sY9iPB8LAQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAsdOV2IqsTV3t3d3NrX2Nnb3d7d29rb297ay7GPYjsf"
            + "CwAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAKHDdbhqjC1Nzb29rZ19ja3N3f3tva29ve2sqwjmA6HgoAAAAA"
            + "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAACRo0V4OlwNLa2tnZ2NfZ2tzd3t3a2drb3djIropdOBwJAAAAAAAAAAAA"
            + "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAcYMVN+ob3P2NjY2NnZ293d3N3b2dna29zVxKmEWDUZCAAAAAAAAAAAAAEAAAAA"
            + "AAAAAAAAAAAAAAAAAAAAAAAGFCxMdpq3y9bX2Nna29ze3tzb2tjY2tva0b6hfFEvFgYAAAABAgMEBQYHBwYFBAIBAAAA"
            + "AAAAAAAAAAAAAAAABBEmRW2RscfT19jZ29vd3t7b2tnY2Nra18u3mHFIKRIFAAEDBQcLDhASFBMSEA0JBgMBAAAAAAAA"
            + "AAAAAAAAAAMMHjpeg6a/z9bZ2tzd3t/e29nZ2Nja2tPDrIpjPSENBAIFCQ4TGR0hJCYlIyEcFRAKBQIBAAAAAAAAAAAA"
            + "AAACCBcvT3SXtMjU2dvd3t/g393b2tra2tfMuJ15UzEZCgUHDRQdJS40OTw/PDo3MCcfFQ0HAwEAAAAAAAAAAAAAAQQP"
            + "Ij5ghKS9ztfa3d7f4N/e3dzd29jRwaeJZEElEgkIDxklMT1IUFVZXFlWU0o/MyYZDwgDAQAAAAAAAAAAAAACCRguTG+Q"
            + "rcPR2Nze3+Dg39/e3dnTxbCTc08wGg0KDxspOUlWYmpucXNwbmtjV0s7KxwQCAMAAAAAAAAAAAAAAAQOHjdWd5aww8/W"
            + "2t3f39/f3dnSxbKYeFk5IRELDRgpO05fbHd+gYSFgoB9dm1hUT4rGg4FAQAAAAAAAAAAAAACCBMlP1x6lqy8xs3S1dfX"
            + "1tPNwa+Ye1w/JhQMCxMjOE1hcn2Gio2PkI2MioZ/dWVRPCYVCQIAAAAAAAAAAAAAAAMKFilBXHePoa+4vsPFxcS/tqaS"
            + "eFxAKRYLCQ4aLkdccH6HjI+Rk5STk5KPi4N1YUoxHA0EAAAAAAAAAAAAAAABBAwYKT5WbICQm6OprKupopaFb1c+KBcL"
            + "BQgRIDdSaHqGi4yNj5GSk5SUk5GMf21VOSIQBQAAAAAAAAAAAAAAAAEECxYlNklaanZ/hoqIhX1wX0w4JRYLBAIHEyU9"
            + "WW5+iIuKiouNj5CSk5OTjoRyWz4lEwYAAAAAAAAAAAAAAAAAAQQKEx4rN0ROVVxfXVpTSDstHxMKBAEBCBQnP1xwgImL"
            + "iIeIiYyOkZKTlJCGdF1AJxQHAAAAAAAAAAAAAAAAAAABAwgOFh4nLjM4Ozk2MSkfFw4IAwEAAAcTJT1Zbn6IioeGhoeJ"
            + "jI+RkpKOg3FaPSUSBgAAAAAAAAAAAAAAAAAAAAACBQgMEhYaHR8eGxgTDQkFAgAAAAAGESA2UWZ4hIiHhYWFiIqNj4+P"
            + "iX1rUzghEAUAAAAAAAAAAAAAAAAAAAAAAAABAwUHCQoMCwoIBgMCAQAAAAAABA0aLUVbbXuChISFhoiJjIyLiIByX0gv"
            + "Gw0DAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABAQEAAAAAAAAAAAAAAAIJEyI3TF5ueH6AgoOGhoeGg3xzY1A6JRQJAgAA"
            + "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABBQwXJzpMXGdxdXl7fn19enRrX049KhkMBQEAAAAAAAAA"
            + "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAIGDhkoN0dTXWRpbHBubWhgVUk5KhsQBwMAAAAAAAAAAAAAAAAA"
            + "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABAwcOGSQxO0ZOVFhcWldRSDwxJBkPCAMBAAAAAAAAAAAAAAAAAAAAAAAA"
            + "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAEDBw0VHSUuNDo9QT88Ni8lHRQNBwMAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
            + "AAAAAAAAAAAAAAAAAAAAAAAAAQMGCg8UGh8jJigmJCAbFA8JBQIBAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
            + "AAAAAAAAAAAAAAAAAAAAAgMGCAwPERMVFBIQDAgFAwEAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
            + "AAAAAAAAAAAAAAAAAQIDBQYHCAcGBQMCAQAAAAAAAAAAAAAA"

    /// RGB triples fed to `skinScore` on its own.
    static let probes: [(Double, Double, Double)] = [
        (60, 197, 26),
        (75, 40, 65),
        (230, 39, 212),
        (125, 114, 195),
        (64, 121, 190),
        (31, 108, 53),
        (202, 59, 88),
        (177, 150, 23),
        (4, 237, 34),
        (179, 112, 233),
        (110, 15, 156),
        (165, 122, 43),
        (136, 33, 70),
        (7, 52, 93),
        (210, 163, 160),
        (89, 30, 255),
        (204, 21, 42),
        (27, 184, 145),
        (246, 247, 100),
        (205, 130, 147),
        (208, 201, 206),
        (239, 252, 133),
        (218, 11, 232),
        (1, 166, 231),
        (148, 61, 50),
        (131, 0, 57),
        (126, 223, 44),
        (245, 138, 251),
        (24, 113, 86),
        (215, 196, 173),
        (226, 115, 48),
        (169, 46, 207),
        (92, 101, 58),
        (235, 72, 225),
        (6, 199, 244),
        (29, 146, 99),
        (96, 25, 222),
        (191, 140, 213),
        (234, 219, 120),
        (81, 182, 183),
        (36, 141, 66),
        (83, 144, 137),
        (142, 175, 188),
        (69, 154, 203),
        (168, 193, 102),
        (167, 84, 253),
        (242, 67, 192),
        (249, 62, 159),
        (236, 181, 74),
        (187, 216, 49),
        (22, 151, 132),
        (109, 162, 51),
        (240, 105, 238),
        (143, 28, 37),
        (250, 171, 8),
        (161, 198, 135),
        (180, 221, 82),
        (35, 32, 217),
        (158, 127, 76),
        (149, 170, 155),
        (56, 17, 118),
        (119, 228, 77),
        (2, 19, 80),
        (73, 78, 111),
        (124, 5, 90),
        (139, 104, 129),
        (38, 103, 20),
        (189, 178, 3),
        (128, 185, 254),
        (95, 172, 117),
        (10, 123, 152),
        (241, 214, 87),
        (68, 45, 98),
        (243, 176, 41),
        (174, 79, 220),
        (229, 186, 107),
        (200, 97, 134),
        (71, 116, 157),
        (18, 227, 224),
        (153, 94, 63),
        (12, 85, 106),
        (91, 248, 209),
        (54, 55, 164),
        (13, 194, 211),
        (16, 9, 14),
        (47, 60, 197),
        (26, 75, 40),
        (65, 230, 39),
        (212, 125, 114),
        (195, 64, 121),
        (190, 31, 108),
        (53, 202, 59),
        (88, 177, 150),
        (23, 4, 237),
        (34, 179, 112),
        (233, 110, 15),
        (255, 255, 255),
        (0, 0, 0),
        (96, 41, 21),
        (95, 40, 20),
        (200, 200, 180),
        (220, 150, 120),
        (180, 120, 100),
        (150, 110, 95),
        (130, 95, 80),
        (240, 200, 190),
        (210, 160, 140),
        (100, 60, 40),
        (250, 128, 114),
    ]

    /// `skinScore` of each probe, from the JS.
    static let probeScores: [Int] = [
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 180,
        0, 0, 228, 0, 0, 0, 0, 127, 0, 0, 0, 0,
        134, 0, 0, 0, 0, 159, 0, 0, 0, 0, 0, 0,
        0, 0, 67, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 255, 0,
        0, 0, 0, 0, 0, 33, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 180, 0, 0, 0, 255, 0, 0, 0, 0,
        0, 0, 0, 0, 134, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 255, 0, 0, 237, 255, 255, 247, 244, 255, 255,
        0,
    ]

    // MARK: - classify() statistics, from the JS

    static let rawPercent = 44
    static let finalPercent = 27
    static let learned = true
    /// JS `stats.learnedCb` / `learnedCr` — the medians the back-projection
    /// learned, which is what `SkinCore.Stats.medianCb` / `medianCr` carry.
    static let learnedCb = 108.4068832397461
    static let learnedCr = 153.044921875
    static let componentsKept = 2
    static let componentsTotal = 3
    static let gain = 1
}
